//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_VLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoes
    {
        public int IdDetalle { get; set; }
        public int IdMenu { get; set; }
        public int IdPedido { get; set; }
        public int cantidad { get; set; }
        public int Estado { get; set; }
        public string Termino { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Menus Menus { get; set; }
        public virtual Pedidoes Pedidoes { get; set; }
    }
}
