//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_VLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompras
    {
        public int IdDetalle { get; set; }
        public double Cantidad { get; set; }
        public double PrecioUnit { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public double PrecioTotal { get; set; }
        public string Codigo { get; set; }
        public int IdProveedor { get; set; }
        public int IdProducto { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
