//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_VLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int NumFactura { get; set; }
        public int IdPedido { get; set; }
        public double TotalNeto { get; set; }
        public double Total { get; set; }
        public double Descuento { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public double Propina { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Pedidoes Pedidoes { get; set; }
    }
}
