//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_VLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int IdPrestamo { get; set; }
        public double Cantidad { get; set; }
        public double CantidadDevuelta { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<System.DateTime> FechaDev { get; set; }
        public int Estado { get; set; }
        public int IdProducto { get; set; }
        public int IdUser { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
