//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_VLO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turnos()
        {
            this.AsignacionTurnoes = new HashSet<AsignacionTurnoes>();
        }
    
        public int IdTurno { get; set; }
        public string Nombre { get; set; }
        public string HoraInicial { get; set; }
        public string HoraFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionTurnoes> AsignacionTurnoes { get; set; }
    }
}
